[package]
name = "webgraph-visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.26"
rerun = { version ="0.22.1" , features = [
  "web_viewer",
  "clap",
] }
webgraph = "0.1.4"
